name: norminette

on: [push, pull_request]

env:
  TERM: xterm-256color

jobs:
  norminette:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v4

    - name: norminette
      uses: alexandregv/norminette-action@v3
      with:
        flags: '.'
