name: test

on: push

env:
  TERM: xterm-256color

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libreadline-dev valgrind

    - name: make test
      run: make test
